# Generated by Django 5.0.6 on 2024-09-09 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('goodsCateKey', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'goodsCategory',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderKey', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.IntegerField()),
                ('rdate', models.DateField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='SituationCategory',
            fields=[
                ('situationCateKey', models.AutoField(primary_key=True, serialize=False)),
                ('situationCategory1', models.CharField(max_length=30)),
                ('situationCategory2', models.CharField(max_length=30)),
                ('situationCategory3', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'situationCategory',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsKey', models.AutoField(primary_key=True, serialize=False)),
                ('ASIN', models.CharField(max_length=30)),
                ('goodsName', models.CharField(max_length=30)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('originalPrice', models.IntegerField()),
                ('discountedPrice', models.IntegerField()),
                ('ratingAvg', models.FloatField(blank=True, null=True)),
                ('ratingCount', models.IntegerField(blank=True, null=True)),
                ('goodsInfo', models.CharField(blank=True, max_length=150, null=True)),
                ('goodsDesc', models.CharField(blank=True, max_length=150, null=True)),
                ('goodsCateKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.goodscategory')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderDetKey', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('cnt', models.IntegerField()),
                ('goodsKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.goods')),
                ('orderKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.orders')),
            ],
            options={
                'db_table': 'orderDetail',
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('situationKey', models.AutoField(primary_key=True, serialize=False)),
                ('headline1', models.CharField(blank=True, max_length=50, null=True)),
                ('headline2', models.CharField(blank=True, max_length=50, null=True)),
                ('mainKeyword', models.CharField(blank=True, max_length=30, null=True)),
                ('situationCateKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.situationcategory')),
            ],
            options={
                'db_table': 'situation',
            },
        ),
        migrations.CreateModel(
            name='SituationKeyword',
            fields=[
                ('situationKwKey', models.AutoField(primary_key=True, serialize=False)),
                ('situationKeyword', models.CharField(max_length=30)),
                ('situationKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.situation')),
            ],
            options={
                'db_table': 'situationKeyword',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userKey', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=50, unique=True)),
                ('userName', models.CharField(max_length=20)),
                ('userPwd', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='userKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.user'),
        ),
    ]
