# Generated by Django 5.0.6 on 2024-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$UxCAH4ImiTw8l2OhIFdkEX$Nvgk9YENhQMmNQ9Cy98Q2UEhiAJm35FUuNYCtjUzVg8=', max_length=128),
        ),
    ]
